Add archlinux package

diff --git a/ulo b/ulo
--- a/ulo
+++ b/ulo
@@ -4,11 +4,19 @@
 # 
 # Licensed under the MIT.
 # 
-lolcat=/usr/games/lolcat
+if [ -f "/usr/bin/lolcat" ]; then
+    lolcat="/usr/bin/lolcat"
+elif [ -f "/usr/games/lolcat" ]; then
+    lolcat="/usr/games/lolcat"
+else
+    echo "Error: lolcat not found. Please install lolcat package."
+    exit 1
+fi
 
+ver="1.2"
 tmp="./tmp"
 out="./out"
-minsize=640
+minsize=768
 
 # SOC
 amlogic=`ls -l ./core/loader/amlogic | grep s9 | awk '{ print $9 }' | cut -d. -f1`
@@ -22,7 +30,10 @@ rootfs_path="./rootfs"
 fwdriver_path="./core/root/lib"
 
 # Kernel & Firmware Repository
-repos="https://github.com/bobbyunknown/ULO-repository"
+repos="https://github.com/armarchindo/ULO-repository"
+
+# Custom ROOTFS Repository on releases
+rootfs_repo="armarchindo/rootfs-openwrt"
 
 start_cnt=$SECONDS
 
@@ -33,26 +44,73 @@ die() {
 
 check_depedencies() {
     echo -e "Preparing install ulo dependies"
-    req=(lolcat pigz aria2 wget)
-    list=`dpkg -l | grep -E "lolcat|pigz|aria2|wget" | awk '{ print $2 }'`
+    req=(lolcat pigz aria2 wget jq dosfstools)
+    
+    if command -v apt >/dev/null 2>&1; then
+        pkg_manager="apt"
+        list=`dpkg -l | grep -E "lolcat|pigz|aria2|wget|jq|dosfstools" | awk '{ print $2 }'`
+    elif command -v pacman >/dev/null 2>&1; then
+        pkg_manager="pacman"
+        list=`pacman -Q | grep -E "lolcat|pigz|aria2|wget|jq|dosfstools" | awk '{ print $1 }'`
+    else
+        echo "Error: Could not find package"
+        exit 1
+    fi
+
     for req_pkg in ${req[*]}; do
+        stat=1
         for lst_pkg in $list; do
-            stat=0
             if [ ${req_pkg} == $lst_pkg ] ; then
                 echo "  $req_pkg Installed"
                 stat=0
-            break;
-            else
-                stat=1
+                break
             fi
         done
+        
         if [[ $stat = 1 ]] ; then
             echo "  Package $req_pkg not found"
             echo "  Installing $req_pkg "
-            apt -y install $req_pkg > /dev/null 2>&1
+            if [ "$pkg_manager" = "apt" ]; then
+                apt -y install $req_pkg > /dev/null 2>&1
+            elif [ "$pkg_manager" = "pacman" ]; then
+                pacman -S --noconfirm $req_pkg > /dev/null 2>&1
+            fi
         fi
     done
     echo -e "Done...!!!" | $lolcat -a -d 20
+}
+
+custom_rootfs_files() {
+    echo -e "Do you want to add additional ROOTFS? (Y/N)"
+    local optz=$1
+    local opt=""
+    local long_url="https://api.github.com/repos/$rootfs_repo/releases"
+    echo -e "$optz"
+    if [ "$optz" = "yes" ]; then
+        opt="Y"
+    elif [ "$optz" = "no" ]; then
+        opt="N"
+    else
+        read -p "" opt 
+    fi
+    if [ "$opt" = "y" ] || [ "$opt" = "Y" ]; then
+        echo -e "Downloading ROOTFS Files..."
+        local cnt=0
+        local json_data=`curl -s $long_url`
+        local list_url=`echo $json_data | jq '.[].assets[].browser_download_url' | tr -d '"'`
+        local list_name=`echo $json_data | jq '.[].tag_name' | tr -d '"'`
+        local list_files=`echo $json_data | jq '.[].assets[].name' | tr -d '"'`
+        for names in ${list_name[*]}; do
+            ((cnt++))
+            echo -e "$cnt. $names"
+        done
+        for urls in ${list_url[*]}; do
+            aria2c -d rootfs "$urls"
+        done
+    else
+        echo -e "Custom ROOTFS skipped..."
+    fi
+    echo -e "Done...!!!"
 }
 
 check_requirement_files() {
@@ -98,6 +156,7 @@ download_requirement_files() {
         rm -r $tmp_path
     fi
     echo -e "All required files are present." | $lolcat -a -d 1
+    custom_rootfs_files
     find_devices
     find_rootfs
     find_kernels
@@ -666,6 +725,7 @@ Options:
     -c, --clean     : Cleaning old cache
     -u, --update    : Update Kernel, ROOTFS, and Firmware files from ULO-Repository
                       (Will Destroy your old Kernel, ROOTFS, and Firmware files!!!)
+    -y  --yes       : Custom ROOTFS Download.
     -k              : set the kernel       (-k 5.9.16)
     -m              : set the device       (-m s905x2)
     -r              : set the rootfs files (-r ImmortalWrt-21.02.7-DBAI-armvirt-rootfs.tar.gz)
@@ -678,7 +738,8 @@ EOF
 echo -e "
 ======================================================================
 ----------------------------------------------------------------------
-                            ULO BUILDER
+                            ULO BUILDER 
+                               v${ver}
                               By DBAI
 ----------------------------------------------------------------------
 ======================================================================
@@ -689,6 +750,10 @@ check_requirement_files
 
 while [ "$1" ]; do
     case "$1" in
+        -y|--yes)
+            custom_rootfs_files "yes"
+            exit
+        ;;
         -h|--help)
             usage
             exit
